In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/flood_data.csv')

In [ ]:
df

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,FLOODS
0,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,1
1,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,1
2,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,1
3,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,1
4,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,4.6,10.3,17.9,95.7,251.0,454.4,677.8,733.9,298.8,355.5,99.5,47.2,1
114,3.1,5.8,50.1,214.1,201.8,563.6,406.0,252.2,292.9,308.1,223.6,79.4,0
115,2.4,3.8,35.9,143.0,186.4,522.2,412.3,325.5,173.2,225.9,125.4,23.6,0
116,1.9,6.8,8.9,43.6,173.5,498.5,319.6,531.8,209.5,192.4,92.5,38.1,0
117,29.1,52.1,48.6,116.4,183.8,625.4,1048.5,1398.9,423.6,356.1,125.4,65.1,1

In [ ]:
# prompt: build a simple ANN mode and save it as .keras model
# accuracy should not be greater tahn 98
# just quick

import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Drop the target variable to create features (X) and keep it separately as target (y)
X = df.drop('FLOODS', axis=1)
y = df['FLOODS']

# Convert categorical features to numerical using one-hot encoding
# Assuming there are no categorical features based on the initial df display.
# If there were, you would use:
# X = pd.get_dummies(X, columns=['CategoricalColumn1', 'CategoricalColumn2'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the ANN model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid') # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
# Use a smaller number of epochs and potentially larger batch size
# to keep accuracy below 98% for a simple model
history = model.fit(X_train_scaled, y_train, epochs=5, batch_size=32, validation_split=0.2, verbose=0)

# Evaluate the model to check accuracy
loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Model Accuracy: {accuracy*100:.2f}%")

# Save the model
model.save('simple_flood_model.keras')

print("Model saved as simple_flood_model.keras")

Model Accuracy: 62.50%
Model saved as simple_flood_model.keras